-- ============================================================================
-- Coach OS â€” PostgreSQL schema + data (Supabase-free edition)
-- ============================================================================
-- ONE file = everything the backend needs: tables, indexes, the full dump of
-- the project KV store (admin + coach accounts, sessions, workspaces, coupons,
-- payments, shop orders, workspace payloads) and SQL that projects that dump
-- into normalized, queryable tables.
--
-- Usage:
--   createdb coach_os
--   psql -d coach_os -f db/schema.sql
--   # or directly with a connection URL:
--   psql "postgres://user:pass@host:5432/coach_os" -f db/schema.sql
--
-- Then point the app at it (server.mjs, Netlify, Docker â€” everywhere):
--   DATABASE_URL=postgres://user:pass@host:5432/coach_os node server.mjs
--
-- Notes:
--   * The DDL section is idempotent: safe to run twice (create if not exists +
--     create or replace + upserts on the static plans seed).
--   * âڑ ï¸ڈ THE DATA SECTION IS NOT A NO-OP ON A LIVE DATABASE. It is a snapshot
--     dump (see the source/date in the KV-DATA header) and every row is an
--     unconditional `insert â€¦ on conflict do update`. Re-running this file
--     against a database that is already serving traffic REVERTS every account
--     (including pass.salt/pass.hash, plan and sub_ends_at), every session and
--     every workspace payload to that snapshot. Run it once on a fresh
--     database; to just create the empty schema, delete the section between
--     the KV-DATA-BEGIN / KV-DATA-END markers first.
--   * No Supabase, no PostgREST, no RLS: the app connects directly with its
--     own Postgres role. Restrict that role with plain GRANTs if needed.
--   * The KV data section between the KV-DATA markers is generated by
--     scripts/export-kv-to-sql.mjs (npm run db:dump). Do not edit by hand.
-- ============================================================================

begin;

-- ---------------------------------------------------------------- 1) KV store
-- The ACTIVE backend. Every app record lives here as "<namespace>:<key>".
-- Namespaces: coach-os-saas       (accounts, sessions, workspaces, billing)
--             coach-os-workspaces (legacy pre-Phase-1.5 bytes)
--             shop-orders         (shop checkout orders + account index)
create table if not exists public.kv_store (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz not null default now()
);
create index if not exists kv_store_updated_at_idx on public.kv_store (updated_at);

-- --------------------------------------------------------------- 2) Admin users
-- Dedicated table for admin-panel credentials. Mirrored automatically from
-- every KV account record with role='admin' (see section 7 below).
create table if not exists public.admin_users (
  id            text primary key,
  email         text unique not null,
  name          text not null default '',
  pass_salt     text not null default '',
  pass_hash     text not null default '',
  role          text not null default 'admin',
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  last_login_at timestamptz null
);

-- --------------------------------------- 3) Normalized SaaS tables (Phase-2 ready)
-- The app currently reads/writes kv_store; these tables are a queryable
-- relational mirror kept in sync by section 7, so reporting, backups and any
-- future phase can go row by row without another deploy.
create table if not exists public.coaches (
  id              text primary key,
  email           text unique not null,
  name            text not null default '',
  pass_salt       text not null default '',
  pass_hash       text not null default '',
  plan            text not null default 'trial',
  workspace_id    text null,
  trial_ends_at   timestamptz null,
  sub_status      text not null default 'trial',
  sub_ends_at     timestamptz null,
  sub_started_at  timestamptz null,
  created_at      timestamptz not null default now()
);
create index if not exists coaches_email_idx on public.coaches (lower(email));

create table if not exists public.sessions (
  token      text primary key,
  coach_id   text not null references public.coaches (id) on delete cascade,
  email      text not null default '',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists sessions_coach_idx on public.sessions (coach_id);
create index if not exists sessions_expires_idx on public.sessions (expires_at);

create table if not exists public.workspaces (
  id             text primary key,
  code           text unique not null,
  owner_coach_id text null references public.coaches (id) on delete set null,
  plan           text not null default 'trial',
  status         text not null default 'trial',
  created_at     timestamptz not null default now(),
  claimed_at     timestamptz null
);
create index if not exists workspaces_code_idx on public.workspaces (code);
create index if not exists workspaces_owner_idx on public.workspaces (owner_coach_id);

create table if not exists public.workspace_data (
  workspace_id text primary key references public.workspaces (id) on delete cascade,
  rev          bigint not null default 0,
  data         jsonb not null default '{}'::jsonb,
  updated_at   timestamptz not null default now()
);

-- ------------------------------------------------- 4) Billing tables (Phase 2)
create table if not exists public.plans (
  id             text primary key,
  name           text not null,
  max_clients    int not null default 5,
  max_storage_mb int not null default 100,
  price_monthly  numeric not null default 0,
  price_currency text not null default 'IRT',
  is_active      boolean not null default true
);

create table if not exists public.coupons (
  code          text primary key,
  plan_id       text not null references public.plans (id),
  duration_days int not null default 30,
  max_uses      int not null default 1,
  used_count    int not null default 0,
  is_active     boolean not null default true,
  expires_at    timestamptz null,
  created_at    timestamptz not null default now()
);

create table if not exists public.payments (
  id            text primary key,
  coach_id      text not null references public.coaches (id) on delete cascade,
  plan_id       text not null default 'trial',
  amount        numeric not null default 0,
  currency      text not null default 'IRT',
  provider      text not null default 'manual',
  tracking_code text not null default '',
  status        text not null default 'pending',
  coupon_code   text null,
  starts_at     timestamptz null,
  ends_at       timestamptz null,
  created_at    timestamptz not null default now()
);
create index if not exists payments_coach_idx on public.payments (coach_id);
create index if not exists payments_status_idx on public.payments (status);

-- ------------------------------------------------------------- 5) Helper + view
-- KV timestamps are epoch milliseconds (jsonb numbers); convert safely.
-- Non-numeric / missing input -> NULL.
-- NOTE: STABLE, not IMMUTABLE. to_timestamp(double precision) is STABLE
-- because its result depends on the session TimeZone. Labelling this wrapper
-- IMMUTABLE is a lie Postgres accepts silently, and it would silently produce
-- stale/incorrect values if it were ever used in an index expression, a
-- generated column or a partition bound.
create or replace function public.ms_to_ts(ms text) returns timestamptz
language sql stable as $$
  select case when ms ~ '^\d+(\.\d+)?$'
              then to_timestamp(ms::double precision / 1000.0) end
$$;

create or replace view public.v_coach_overview as
select c.id, c.email, c.name, c.plan, c.sub_status, c.sub_ends_at, c.created_at,
       w.code as workspace_code, w.status as workspace_status,
       d.rev as data_rev, d.updated_at as data_updated_at
from public.coaches c
left join public.workspaces w on w.id = c.workspace_id
left join public.workspace_data d on d.workspace_id = w.id;

-- ------------------------------------------------------- 6) Static seed: plans
-- Mirrors PLANS in netlify/lib/billing.mjs (server-authoritative).
insert into public.plans (id, name, max_clients, max_storage_mb, price_monthly, price_currency, is_active) values
  ('trial',        'Trial',        5,   100,   0,       'IRT', true),
  ('basic',        'Basic',        5,   100,   290000,  'IRT', true),
  ('professional', 'Professional', 30,  2048,  790000,  'IRT', true),
  ('club',         'Club',         200, 10240, 2490000, 'IRT', true)
on conflict (id) do update set
  name = excluded.name,
  max_clients = excluded.max_clients,
  max_storage_mb = excluded.max_storage_mb,
  price_monthly = excluded.price_monthly,
  price_currency = excluded.price_currency,
  is_active = excluded.is_active;

-- ============================================================================
-- 7) DATA â€” full dump of the project KV store (admin + everything else)
-- ============================================================================
-- >>> FRESH SCHEMA: data dump intentionally omitted (production starts empty).
-- <<< KV-DATA-END

-- ============================================================================
-- 8) Project the KV dump into the normalized tables (queryable mirror)
-- ============================================================================
-- Pure SQL derived from the kv_store rows above, so the mirror is always in
-- sync with the dump and the whole file stays idempotent/re-runnable.

-- coaches <- acct:<email>
insert into public.coaches as c (id, email, name, pass_salt, pass_hash, plan, workspace_id,
                                 trial_ends_at, sub_status, sub_ends_at, sub_started_at, created_at)
select v->>'id',
       lower(v->>'email'),
       coalesce(v->>'name', ''),
       coalesce(v #>> '{pass,salt}', ''),
       coalesce(v #>> '{pass,hash}', ''),
       coalesce(v->>'plan', 'trial'),
       nullif(v->>'workspaceId', ''),
       public.ms_to_ts(v->>'trialEndsAt'),
       coalesce(v->>'sub_status', 'trial'),
       public.ms_to_ts(v->>'sub_ends_at'),
       public.ms_to_ts(v->>'sub_started_at'),
       coalesce(public.ms_to_ts(v->>'createdAt'), now())
from (select value as v from public.kv_store where key like 'coach-os-saas:acct:%') s
where v->>'id' is not null and v->>'email' is not null
on conflict (id) do update set
  email = excluded.email, name = excluded.name,
  pass_salt = excluded.pass_salt, pass_hash = excluded.pass_hash,
  plan = excluded.plan, workspace_id = excluded.workspace_id,
  trial_ends_at = excluded.trial_ends_at, sub_status = excluded.sub_status,
  sub_ends_at = excluded.sub_ends_at, sub_started_at = excluded.sub_started_at;

-- admin_users <- acct:<email> where role='admin'
insert into public.admin_users as a (id, email, name, pass_salt, pass_hash, role, created_at)
select v->>'id',
       lower(v->>'email'),
       coalesce(v->>'name', ''),
       coalesce(v #>> '{pass,salt}', ''),
       coalesce(v #>> '{pass,hash}', ''),
       coalesce(v->>'role', 'admin'),
       coalesce(public.ms_to_ts(v->>'createdAt'), now())
from (select value as v from public.kv_store where key like 'coach-os-saas:acct:%') s
where v->>'id' is not null and v->>'email' is not null and v->>'role' = 'admin'
on conflict (id) do update set
  email = excluded.email, name = excluded.name,
  pass_salt = excluded.pass_salt, pass_hash = excluded.pass_hash, role = excluded.role;

-- workspaces <- ws:<id>  (owner "coach:<id>" -> owner_coach_id, only if it exists)
insert into public.workspaces as w (id, code, owner_coach_id, plan, status, created_at, claimed_at)
select v->>'id',
       v->>'code',
       case when v->>'owner' like 'coach:%'
             and exists (select 1 from public.coaches c
                         where c.id = substring(v->>'owner' from 7))
            then substring(v->>'owner' from 7) end,
       coalesce(v->>'plan', 'trial'),
       coalesce(v->>'status', 'trial'),
       coalesce(public.ms_to_ts(v->>'createdAt'), now()),
       public.ms_to_ts(v->>'claimedAt')
from (select value as v from public.kv_store where key like 'coach-os-saas:ws:%') s
where v->>'id' is not null and v->>'code' is not null
on conflict (id) do update set
  code = excluded.code, owner_coach_id = excluded.owner_coach_id,
  plan = excluded.plan, status = excluded.status,
  created_at = excluded.created_at, claimed_at = excluded.claimed_at;

-- sessions <- sess:<token>  (skip orphans whose coach no longer exists)
insert into public.sessions (token, coach_id, email, created_at, expires_at)
select substring(key from length('coach-os-saas:sess:') + 1),
       v->>'coachId',
       coalesce(v->>'email', ''),
       coalesce(public.ms_to_ts(v->>'createdAt'), now()),
       coalesce(public.ms_to_ts(v->>'expiresAt'), now() + interval '30 days')
from (select key, value as v from public.kv_store where key like 'coach-os-saas:sess:%') s
where v->>'coachId' is not null
  and exists (select 1 from public.coaches c where c.id = v->>'coachId')
on conflict (token) do update set
  email = excluded.email, created_at = excluded.created_at, expires_at = excluded.expires_at;

-- workspace_data <- ws-meta:<wid>
insert into public.workspace_data as d (workspace_id, rev, data, updated_at)
select substring(key from length('coach-os-saas:ws-meta:') + 1),
       coalesce((v->>'rev')::bigint, 0),
       coalesce(v->'data', '{}'::jsonb),
       coalesce(public.ms_to_ts(v->>'updatedAt'), now())
from (select key, value as v from public.kv_store where key like 'coach-os-saas:ws-meta:%') s
where exists (select 1 from public.workspaces w
              where w.id = substring(key from length('coach-os-saas:ws-meta:') + 1))
on conflict (workspace_id) do update set
  rev = excluded.rev, data = excluded.data, updated_at = excluded.updated_at;

-- coupons <- coupon:<CODE>
insert into public.coupons as cp (code, plan_id, duration_days, max_uses, used_count,
                                  is_active, expires_at, created_at)
select v->>'code',
       coalesce(v->>'planId', 'basic'),
       coalesce((v->>'durationDays')::int, 30),
       coalesce((v->>'maxUses')::int, 1),
       coalesce((v->>'usedCount')::int, 0),
       coalesce((v->>'isActive')::boolean, true),
       public.ms_to_ts(v->>'expiresAt'),
       coalesce(public.ms_to_ts(v->>'createdAt'), now())
from (select value as v from public.kv_store where key like 'coach-os-saas:coupon:%') s
where v->>'code' is not null
  and exists (select 1 from public.plans p where p.id = coalesce(v->>'planId', 'basic'))
on conflict (code) do update set
  plan_id = excluded.plan_id, duration_days = excluded.duration_days,
  max_uses = excluded.max_uses, used_count = excluded.used_count,
  is_active = excluded.is_active, expires_at = excluded.expires_at;

-- payments <- pay:<id>
insert into public.payments as pay (id, coach_id, plan_id, amount, currency, provider,
                                    tracking_code, status, coupon_code, starts_at, ends_at, created_at)
select v->>'id',
       v->>'coachId',
       coalesce(v->>'planId', 'trial'),
       coalesce((v->>'amount')::numeric, 0),
       coalesce(v->>'currency', 'IRT'),
       coalesce(v->>'provider', 'manual'),
       coalesce(v->>'tracking', ''),
       coalesce(v->>'status', 'pending'),
       -- The app never writes a `couponCode` field: coupon payments carry the
       -- code in `tracking` (see netlify/lib/billing.mjs redeem()). Reading
       -- only `couponCode` left this column permanently NULL, so the coupon
       -- code actually lived in tracking_code and coupon_code was dead weight.
       coalesce(nullif(v->>'couponCode', ''),
                case when coalesce(v->>'provider', '') = 'coupon'
                     then nullif(v->>'tracking', '') end),
       public.ms_to_ts(v->>'startsAt'),
       public.ms_to_ts(v->>'endsAt'),
       coalesce(public.ms_to_ts(v->>'createdAt'), now())
from (select value as v from public.kv_store where key like 'coach-os-saas:pay:%') s
where v->>'id' is not null
  and exists (select 1 from public.coaches c where c.id = v->>'coachId')
on conflict (id) do update set
  plan_id = excluded.plan_id, amount = excluded.amount, currency = excluded.currency,
  provider = excluded.provider, tracking_code = excluded.tracking_code,
  status = excluded.status, coupon_code = excluded.coupon_code,
  starts_at = excluded.starts_at, ends_at = excluded.ends_at;

commit;

-- ============================================================================
-- 9) Quick verification (psql)
-- ============================================================================
--   select backend-ish counts:
--     select count(*) from public.kv_store;            -- raw records
--     select count(*) from public.coaches;             -- includes the admin
--     select * from public.v_coach_overview;           -- admin panel view
--   The main admin row:
--     select id, email, role from public.admin_users;
